import {DM_Sans} from 'next/font/google'
import './globals.css';

export const dmSans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm-sans'
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={`${dmSans.variable} antialiased`}>
      <body
        
      >
        {children}
      </body>
    </html>
  );
}
